### ISSUE TITLE
RV64G examples on bare_etiss_processor

### ISSUE THREAD

**Issue by uzleosharif** [tum-ei-eda/etiss#46]
do we want to support RV64G ISA in examples? Currently i see that:
* the `SW` in examples forces `march=rv32gc` and `mabi` for gcc. Though you can set it up in the CMake script but the README doesn't mention this option
* the `rv64` in `run_helper.sh` doesn't seem to work as ETISS crashes with unrecognized option

**Comment by rafzi** [comment]
The rv64 option is obsolete, because the architecture is now determined by reading the ELF file headers.

You can configure march and mabi, but this is still undocumented.

I had to fix something in the toolchain file, but then it worked for me and the CI:

https://github.com/tum-ei-eda/etiss/commit/e785480304d82cf230468581b46d09f8bc305b0c
